spring:
  application:
    name: flowcontrol
  datasource:
#    url: jdbc:mariadb://neobns.com:13306/db2
#    username: POC_USER
#    password: neobns1!
#    driver-class-name: org.mariadb.jdbc.Driver
    password: 1234
    username: root
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: localhost
  filters:
    group1: resilience4j
    group2: bucket4j
  jwt:
    secret: c2VjcmV0S2V5VmFsaGF2ZXRvYmVTdHJvbmdlbm91Z2g=

server:
  port: 8081
mybatis:
  mapper-locations: classpath:mappers/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"