spring:
  application:
    name: flowAdmin
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://neobns.com:13306/db2
    username: POC_USER
    password: neobns1!
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true