server:
  port: 3311
  
spring:  
  application:
    name: spider-batch

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mariadb.sql

spider:
  batch:
    datasource-batch:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://neobns.com:13306/db1
      username: POC_USER
      password: neobns1!
    datasource-common:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://neobns.com:13306/db2
      username: POC_USER
      password: neobns1!
    datasource-target:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://neobns.com:13306/db3
      username: POC_USER
      password: neobns1!
    datasource-spiderdb:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@//neobns.com:11521/XE
      username: system
      password: oracle